### ISSUE TITLE
[Bug] 게임 시작시 서버 죽음.

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-09#362]
![image](https://user-images.githubusercontent.com/31912670/70297852-f8cf7b80-1832-11ea-9799-ad1d16e31ebc.png)

**Comment by JeongHyeonJo** [comment]
카메라를 허용하지 않을 경우 생기는 에러입니다.
현재 수정중이고, 버그를 해결하면 배포버전에도 적용시키겠습니다.

**Comment by younguna** [comment]
해당 문제는 해결되어 배포되었습니다. 감사합니다.
