### ISSUE TITLE
[bug] 닉네임 빈칸이 됩니다.

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-09#366]
<img width="137" alt="스크린샷 2019-12-06 오후 2 55 24" src="https://user-images.githubusercontent.com/6429885/70299534-7fd32280-1838-11ea-90d5-05c0570dcec2.png">

스페이스로만 닉네임을 했는데 제대로 접속되네요

**Comment by younguna** [comment]
닉네임 빈칸 체크하여 빈칸이면 진행되지 않도록 구현했습니다.
#373
