### ISSUE TITLE
[bug] 사파리에서 랭킹 문제

### ISSUE THREAD

**Issue by FullOfOrange** [connect-foundation/2019-09#368]
맥 OS
사파리 브라우저에서 랭킹 스크롤시 다음과 같이 된다.

<img width="422" alt="스크린샷 2019-12-06 오후 3 15 03" src="https://user-images.githubusercontent.com/10372359/70300844-f9204480-183b-11ea-8c50-5447c2dc028e.png">

**Comment by younguna** [comment]
위 문제는 저희 데모가 아닙니다.

**Comment by FullOfOrange** [comment]
죄송합니다
