### ISSUE TITLE
새로고침을 반복할 경우, 플레이어가 늘어나고, 게임의 룸 인원에 오류가 생기는 현상

### ISSUE THREAD

**Issue by JeongHyeonJo** [connect-foundation/2019-09#411]
게임에 들어가고 새로고침을 반복할 경우,
유저가 처음 화면으로 돌아가는 경우와
클라이언트의 유저에 인원이 추가(복사) 되어 나타남

필요 : 새로고침을 할 경우, 게임 룸에 다시 들여보내는 것이 아니라
메인 페이지로 돌아가게 하는 로직 필요함

**Comment by younguna** [comment]
해당 문제가 해결되어 배포완료 되었습니다.
