### ISSUE TITLE
[bug] 닉네임 5글자 초과 시 축약돼서 나오는 부분 hover시 풀네임이 나오는게 맞을거 같아요

### ISSUE THREAD

**Issue by eastgerm** [connect-foundation/2019-09#457]
공간제약 상 축약이 이뤄졌으나 그래도 본래 닉네임은 다른 어떤 방식으로라도 확인이 가능한게 좋을거 같아요

**Comment by younguna** [comment]
해당 문제는 닉네임 공간을 늘림으로 부분적으로 해결하였습니다. hover시  나타나는 fullname이 나오는 기능은 현재 더 시급한 사항들을 다루는 중에 있기때문에 추후에 고려하도록 하겠습니다.
감사합니다.
