### ISSUE TITLE
[bug] 정답을 계속 맞출 수 있어요

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-09#458]
<img width="873" alt="스크린샷 2019-12-13 오후 2 52 57" src="https://user-images.githubusercontent.com/6429885/70772599-5d04b900-1db8-11ea-8b3f-45e6c2432a84.png">

- 정답을 지속적으로 제출할 수 있어요
- 계속해서 점수가 올라갑니다

**Comment by gyustar** [comment]
맞아요 그래서 저 지금 2000점 넘음ㅎ

**Comment by gyustar** [comment]
그리고 이 화면에서 정답 계속 맞추면 타이머가 안내려가서 무한반복이에요

**Comment by younguna** [comment]
위 문제는 해결되어 배포되었습니다.
제보 감사합니다.
