### ISSUE TITLE
[bug] 최초 정답자가 나왔는데도 일정 시간 내에 답을 적었을 경우 정답자로 또 나오는거 같습니다

### ISSUE THREAD

**Issue by eastgerm** [connect-foundation/2019-09#459]
'장기원안좋아' 최초 정답
'jongnana' 이후에도 정답

![image](https://user-images.githubusercontent.com/44774582/70772771-e4522c80-1db8-11ea-98eb-5a6482dfc110.png)

**Comment by JeongHyeonJo** [comment]
서버에서 2번 정답 로직이 없던 문제인 것 같습니다. 테스트 감사합니다.

**Comment by younguna** [comment]
해당 문제는 해결되어 배포되었습니다. 감사합니다.
