### ISSUE TITLE
[질문] 카메라 사용 허용은 사용자가 직접 해 주어야 하는 건가요!?

### ISSUE THREAD

**Issue by samrho** [connect-foundation/2019-09#461]
사용 브라우저: 크롬
사용 OS: OSX Catalina

---
훌륭하게 잘 작동하는군요!

카메라 사용 허용은 사용자가 직접 해 주어야 하는 건가요!?
처음에 '사용 허용하지 않음'을 누르고 다시 접속하려 할 때,
사용자가 어떻게 해야 할지 모를 수 있을 것 같다는 생각이 들었습니다. 

그리고, 대기중에 그냥 튕겨버리는 현상이 몇 번 발생하는 것을 보았습니다.

**Comment by JeongHyeonJo** [comment]
대기중에 팅기는 현상은 레디를 20초 안에 하지 않을 경우 발생하는 일입니다.
카메라는 지금은 직접 허용해주어야 합니다.
