### ISSUE TITLE
[bug] 카메라 허용을 안하면 게임이 안되요

### ISSUE THREAD

**Issue by Einere** [connect-foundation/2019-09#462]
알럴트 창 확인하면 튕기는데.. 보통 설정창 띄워주지 않나여?
설정 방법을 알려주던지, 아니면 설정창을 띄워주는게 좋을 거 같아여

**Comment by younguna** [comment]
설정하는 방법에 대한 페이지로 안내하는 기능이 추후에 추가될 예정입니다.
감사합니다.
