### ISSUE TITLE
[BUG] 카메라 허용을 해도 들어가지가 않아져요

### ISSUE THREAD

**Issue by hzoou** [connect-foundation/2019-09#463]
![](https://media.giphy.com/media/MAub9D5ztt2rRljMVR/giphy.gif)

**Comment by younguna** [comment]
위 부분은 OS가 브라우저에 카메라 허용 권한을 주지 않는 문제로 보입니다.
추후 위를 허용해주는 안내페이지를 추가할 예정입니다.
감사합니다.
