### ISSUE TITLE
[bug] 문제내는 사람이 채팅에 정답을 말할 수 있어요

### ISSUE THREAD

**Issue by gyustar** [connect-foundation/2019-09#464]
정답 유출 가능

**Comment by younguna** [comment]
이 부분은 사실 기획적으로 의도된 부분입니다. 
하지만 경쟁 시스템에서 자신이 내는 문제에 대한 답을 유출하는 것은 자신에게 불리한 부분이기 때문에 따로 처리를 하지 않았습니다.
이 부분이 추후 문제가 많이 된다면 고려해 보도록 하겠습니다.
